default_platform(:ios)

platform :ios do
  lane :build_app_lane do

    team_id = ENV["IOS_TEAM_ID"]
    bundle_id = ENV["BUNDLE_ID"]
    profile_name = ENV["IOS_PROFILE_NAME"]

    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      configuration: "Release",
      export_method: "app-store",
      xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY=\"Apple Distribution\" DEVELOPMENT_TEAM=#{team_id} PROVISIONING_PROFILE_SPECIFIER=\"#{profile_name}\" -allowProvisioningUpdates",
      export_xcargs: "-allowProvisioningUpdates DEVELOPMENT_TEAM=#{team_id}",
      export_team_id: team_id,
      export_options: {
        method: "app-store",
        teamID: team_id,
        signingStyle: "manual",
        provisioningProfiles: {
          bundle_id => profile_name
        }
      }
    )
  end
end
